services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always

  backend:
    build:
      context: ./backend
    depends_on:
      - db
    environment:
      - PORT=5000
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=app_db
      - DB_USER=admin
      - DB_PASSWORD=securepassword
    restart: always

  db:
    build:
      context: ./database
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=app_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=securepassword
    restart: always

volumes:
  db_data: