global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'backend'
    static_configs:
      - targets: ['backend:5000']
        labels:
          app: 'backend'
    metrics_path: '/metrics'
  - job_name: 'postgres'
    static_configs:
      - targets: ['db:5432']
        labels:
          app: 'postgres'